version: "3.8"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: order_db
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_password
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uorder_user", "-porder_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-service:
    build:
      context: ./services/api-service
    container_name: api-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=order_user
      - DB_PASSWORD=order_password
      - DB_NAME=order_db
      - MQ_HOST=rabbitmq
    depends_on:
      mysql_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer-service:
    build:
      context: ./services/consumer-service
    container_name: consumer-service
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=order_user
      - DB_PASSWORD=order_password
      - DB_NAME=order_db
      - MQ_HOST=rabbitmq
      - INCOMING_ORDER_QUEUE=order_created_queue
      - DLQ_EXCHANGE=order_dlx
      - DLQ_QUEUE=order_created_dlq
      - RETRY_QUEUE=order_retry_queue
      - MAX_RETRIES=3
    depends_on:
      mysql_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  outbox-relayer:
    build:
      context: ./services/consumer-service
    container_name: outbox-relayer
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=mysql_db
      - DB_USER=order_user
      - DB_PASSWORD=order_password
      - DB_NAME=order_db
      - MQ_HOST=rabbitmq
      - OUTGOING_PROCESSED_TOPIC=order_processed_topic
    depends_on:
      mysql_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: ["/entrypoint_relayer.sh"]
